const DATASYNC_TYPE_ADD = "1"
const DATASYNC_TYPE_DELETE = "2"
const DATASYNC_TYPE_UPDATE = "3"
const DATASYNC_TYPE_BLOCK = "5"
const DATASYNC_TYPE_UNBLOCK = "6"

module.exports = {
    DATASYNC_TYPE_ADD,
    DATASYNC_TYPE_DELETE,
    DATASYNC_TYPE_UPDATE,
    DATASYNC_TYPE_BLOCK,
    DATASYNC_TYPE_UNBLOCK,
}